### ISSUE TITLE
Potential Issue - Boss not using every row (Trapper and Pelter)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [julian-perge/InscryptionMods#2]
![02i4JFI 1](https://user-images.githubusercontent.com/10351221/147664965-ed043b8d-8986-4dbf-b6a2-38e4983554bf.png)

**Comment by julian-perge** [comment]
I believe this is just cosmetic, mostly.

All other fights will use each row, although the trapper's blueprint may need to be modified to use all slots.

**Comment by julian-perge** [comment]
Looked into this, and this is just how the Trapper/Trader is setup to start the round. Next turn they will start playing cards in all slots.
