### ISSUE TITLE
Cosmetic Issue - Leshy Moon Battle 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [julian-perge/InscryptionMods#3]
![SKaIs1L 1](https://user-images.githubusercontent.com/10351221/147676038-6a5c40bd-a886-4838-89f2-9f4567a23513.png)

**Comment by julian-perge** [comment]
Thanks for reporting this.

I noticed it last night as well and worked on creating a fix but have not finished it.

There's a problem I'm having loading a different image texture, but hope I can figure it out this week.

**Comment by julian-perge** [comment]
![image](https://user-images.githubusercontent.com/3217992/147833188-8fef70b3-7e0b-40fc-9c58-111f49b6ab6e.png)

This has now been fixed.
