### ISSUE TITLE
Firepit Mod not working with Kaycee mod.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [julian-perge/InscryptionMods#6]
I like the two boost limit from kaycee's mod but fire pit isn't guaranteed to work with this mod. I will keep testing for you though.

**Comment by julian-perge** [comment]
Looks like there was a code update with KC on how that value is determined.

Before:
```
float num2 = 1f - (float)numBuffsGiven * 0.225f;
if (SeededRandom.Value(SaveManager.SaveFile.GetCurrentRandomSeed()) > num2)
```

With KC:
```
float odds = SaveFile.IsAscension ? 0.5f : (1f - (float)numBuffsGiven * 0.225f);
bool flag9 = SeededRandom.Value(SaveManager.SaveFile.GetCurrentRandomSeed()) > odds;
```

**Comment by julian-perge** [comment]
This should now be fixed: https://github.com/julian-perge/InscryptionMods/commit/45a55a5fe7f1be3fb07ecab7c5800305518105c1

**Comment by julian-perge** [comment]
Should now be fixed correctly this time.
